version: '3'

services:
  puppeteer-fedora:
    build:
      context: fedora
      dockerfile: fedora/Dockerfile
    volumes:
      - ./fedora:/app
      - ./main.py:/app/
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: host

  puppeteer-debian:
    build:
      context: debian
      dockerfile: debian/Dockerfile
    volumes:
      - ./debian:/app
      - ./main.py:/app/
    environment:
      - DISPLAY=${DISPLAY}
    network_mode: host
